---
.in-gradle-environment:
  image: "gradle:${GRADLE_VERSION}"
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  interruptible: true
  tags:
    - docker
  variables:
    GRADLE_VERSION: "6.7.1-jdk8"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
